### ISSUE TITLE
Error converting Agilent data due to missing MsProfile.bin

### ISSUE THREAD

**Issue by jwinget** [PNNL-m-q/mza#3]
Hello, this is my first time trying out `mza`. I want to convert data collected on an Agilent 6560, but the instrument was _not_ run in IM mode (qToF only).

I called mza with the standard command: `.\mza.exe -file .\2024-11-07 -extension .d -intensityThreshold 20`
This yields the following output:
```
Processing file: .\2024-11-07\MPA-0002.d
Traceback (most recent call last):
  File "mza.py", line 88, in <module>
  File "mza.py", line 24, in write_mza
  File "source\AgilentIMd2mza.py", line 54, in write_mza_from_agilentimd
  File "source\AgilentIMdReader.py", line 63, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '.\\2024-11-07\\MPA-0002.d\\AcqData\\MsProfile.bin'
[21888] Failed to execute script 'mza' due to unhandled exception!
```

I looked in the indicated folder, and there is in fact no MsProfile.bin within it. I suspect that this might be because I stored the data in centroid mode during collection. Does `mza` require profile data?

**Comment by aivett** [comment]
Hello, thank you for trying mza. My apologies for the delayed reply. 
Yes, mza requires profile data, centroid data is ignored. 
MZA works for QTOF data not run in IM mode, but it needs to be collected in profile mode. If you have the original .d data file with profile data please try the latest mza release and let me know if you have any other issue.
